# -*- coding: utf-8 -*-
"""DataAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFMfU9UoEjjq7U-BnGCao3fsaQulaEm7
"""

import pandas as pd

df=pd.read_csv("/content/Titanic-Dataset.csv")

df

df.info()

# df.describe()
df.select_dtypes(include='number').corr()['Age']

"""#Univariate Analysis

"""

import matplotlib.pyplot as plt

plt.hist(df['Age'], bins=50)
plt.show()

import seaborn as sns

sns.kdeplot(df['Pclass'])

sns.countplot(df['Sex'])

"""#Multivariate Analysis

"""

df1=pd.read_csv("/content/Balaji Fast Food Sales.csv")

df1

import seaborn as sns

sns.scatterplot(x=df1['item_price'],y=df1['transaction_amount'], hue=df1['item_type'],style=df1['transaction_type'])

# sns.barplot(x=df1['transaction_amount'],y=df1['transaction_type'])
sns.displot(df1[df1['transaction_type']=='Cash'], x='transaction_amount', kind='hist')
sns.displot(df1[df1['transaction_type']=='Online'], x='transaction_amount', kind='hist')

sns.heatmap(pd.crosstab(df1['item_type'],df1['time_of_sale']))

sns.clustermap(pd.crosstab(df1['item_type'],df1['time_of_sale']))

sns.lineplot(x=df1['item_price'],y=df1['item_type'])

import seaborn as sns

sns.histplot(df1['item_type'])

from ydata_profiling import ProfileReport

profile = ProfileReport(df1)
profile.to_file("output.html")